language: julia
os:
  - linux
  - osx
julia:
  - 0.6
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("PulseAudio"); Pkg.test("PulseAudio"; coverage=true)'
after_success:
- julia -e 'cd(Pkg.dir("PulseAudio")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
